openapi: 3.0.3
info:
  title: 'Documentação da API vivily'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths: []
tags: []
components:
  securitySchemes:
    default:
      type: apiKey
      name: Authorization
      in: header
      description: ''
security:
  -
    default: []
